# Generated by Django 4.2.7 on 2024-06-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miningaction',
            old_name='wealth',
            new_name='value',
        ),
    ]
