# Generated by Django 4.2.7 on 2024-08-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0003_miningaction_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miningaction',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
