# Generated by Django 4.2.3 on 2023-08-10 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secret_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=64)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('can_be_added_to_contacts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('secret_message_description_emoji', models.CharField(default='📩', max_length=16)),
                ('secret_message_button_emoji', models.CharField(default='👀', max_length=16)),
                ('secret_message_button_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='secret_messages.secretmessagebuttontemplate')),
                ('secret_message_description_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='secret_messages.secretmessagedescriptiontemplate')),
            ],
        ),
    ]
