# Generated by Django 4.2.3 on 2023-07-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('fullname', models.CharField(max_length=64)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('is_premium', models.BooleanField(default=False)),
            ],
        ),
    ]
