# Generated by Django 4.2.4 on 2023-08-10 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_be_added_to_contacts',
        ),
        migrations.AddField(
            model_name='preferences',
            name='can_be_added_to_contacts',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_name', models.CharField(max_length=32)),
                ('public_name', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('of_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='of_user', to='users.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='users.user')),
            ],
            options={
                'unique_together': {('of_user', 'to_user')},
            },
        ),
    ]
