# Generated by Django 4.2.4 on 2023-08-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
