# Generated by Django 4.2.3 on 2023-08-10 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secret_messages', '0004_secretmessagetemplate_and_more'),
        ('users', '0003_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_message_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='secret_messages.secretmessagetemplate'),
        ),
    ]
