# Generated by Django 4.2.7 on 2023-12-31 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_secret_message_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_started_at',
        ),
    ]
