# Generated by Django 4.2.7 on 2024-03-12 17:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_born_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('secret_message_template_text', models.CharField(default='📩 Секретное сообщение для <b>{name}</b>', max_length=255)),
                ('secret_media_template_text', models.CharField(default='📩 Секретное медиа-сообщение для <b>{name}</b>', max_length=255)),
                ('secret_message_view_button_text', models.CharField(default='👀 Прочитать', max_length=32)),
                ('secret_message_delete_button_text', models.CharField(default='❌ Передумать', max_length=32)),
                ('secret_message_read_confirmation_text', models.CharField(default='📩 Секретное сообщение для <b>{name}</b> прочитано\n\n{text}', max_length=255)),
                ('secret_message_deleted_confirmation_text', models.CharField(default='✅ Секретное сообщение удалено', max_length=255)),
                ('secret_message_deleted_text', models.CharField(default='❌ Секретное сообщение было удалено отправителем', max_length=255)),
                ('secret_message_missing_text', models.CharField(default='😔 Сообщение не найдено. Возможно оно ещё не загружено на наши сервера. Попробуйте через пару секунд', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.CheckConstraint(check=models.Q(('secret_message_template_text__contains', '{name}')), name='secret_message_template_text_contains_name', violation_error_message='Secret message template text must contain "{name}"'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.CheckConstraint(check=models.Q(('secret_media_template_text__contains', '{name}')), name='secret_media_template_text_contains_name', violation_error_message='Secret media template text must contain "{name}"'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.CheckConstraint(check=models.Q(('secret_message_read_confirmation_text__contains', '{name}'), ('secret_message_read_confirmation_text__contains', '{text}')), name='secret_message_read_confirmation_text_contains_name_and_text', violation_error_message='Secret message read confirmation text must contain "{name} and {text}"'),
        ),
    ]
