# Generated by Django 4.2.7 on 2024-03-13 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_theme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='secret_message_theme',
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.theme'),
        ),
    ]
