# Generated by Django 4.2.7 on 2024-03-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_user_secret_message_theme_user_theme'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='user',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
