# Generated by Django 4.2.7 on 2024-03-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_teammember_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked_bot',
            field=models.BooleanField(default=False),
        ),
    ]
