# Generated by Django 4.2.7 on 2024-04-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_is_blocked_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='born_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personality_type_prefix',
            field=models.CharField(blank=True, choices=[('INTJ', 'Стратег (INTJ)'), ('INTP', 'Ученый (INTP)'), ('ENTJ', 'Командир (ENTJ)'), ('ENTP', 'Полемист (ENTP)'), ('INFJ', 'Активист (INFJ)'), ('INFP', 'Посредник (INFP)'), ('ENFJ', 'Тренер (ENFJ)'), ('ENFP', 'Борец (ENFP)'), ('ISTJ', 'Администратор (ISTJ)'), ('ISFJ', 'Защитник (ISFJ)'), ('ESTJ', 'Менеджер (ESTJ)'), ('ESFJ', 'Консул (ESFJ)'), ('ISTP', 'Виртуоз (ISTP)'), ('ISFP', 'Артист (ISFP)'), ('ESTP', 'Делец (ESTP)'), ('ESFP', 'Развлекатель (ESFP)')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personality_type_suffix',
            field=models.CharField(blank=True, choices=[('A', 'Assertive'), ('T', 'Turbulent')], max_length=1, null=True),
        ),
    ]
