# Generated by Django 4.2.7 on 2024-06-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_fullname_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts_sorting_strategy',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Creation Time'), (2, 'Public Name'), (3, 'Private Name')], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='is_contacts_sorting_reversed',
            field=models.BooleanField(default=False),
        ),
    ]
