# Generated by Django 4.2.7 on 2024-06-16 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_contacts_sorting_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='energy',
            field=models.PositiveSmallIntegerField(default=5000, validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
