# Generated by Django 4.2.7 on 2024-06-18 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='health',
            field=models.PositiveSmallIntegerField(default=10000, validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
