# Generated by Django 4.2.7 on 2024-03-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1024, unique=True)),
                ('day', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
            ],
            options={
                'unique_together': {('month', 'day')},
            },
        ),
    ]
