# Generated by Django 4.2.7 on 2024-03-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('month', 'day', 'name')},
        ),
    ]
