# Generated by Django 4.2.7 on 2023-12-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='source',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('sender__isnull', False), ('recipient__isnull', False), _connector='OR'), name='either_sender_or_recipient'),
        ),
    ]
