# Generated by Django 4.2.7 on 2023-12-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0003_remove_transaction_either_sender_or_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='either_sender_or_recipient',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('sender__isnull', False), ('recipient__isnull', False), _connector='OR'), name='either_sender_or_recipient', violation_error_message='Transaction must have at least either sender or recipient'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('sender', models.F('recipient')), _negated=True), name='sender_not_equal_recipient', violation_error_message='Sender and recipient must not be equal'),
        ),
    ]
