# Generated by Django 4.2.4 on 2023-08-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contact_profile_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='profile_photo_url',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
