# Generated by Django 4.2.4 on 2023-08-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_receive_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
