# Generated by Django 4.2.4 on 2023-08-25 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_team_teammember'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'user')},
        ),
    ]
