# Generated by Django 4.2.4 on 2023-08-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_teammember_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='born_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
