# Generated by Django 4.2.4 on 2023-09-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secret_messages', '0003_secretmessagetheme_is_hidden'),
        ('users', '0010_user_born_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret_message_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secret_messages.secretmessagetheme'),
        ),
    ]
