# Generated by Django 4.2.7 on 2024-01-02 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0012_remove_user_subscription_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ManasId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('born_at', models.DateField()),
                ('course', models.PositiveSmallIntegerField(choices=[(1, 'Preparation'), (2, 'Bachelor First'), (3, 'Bachelor Second'), (4, 'Bachelor Third'), (5, 'Bachelor Fourth')])),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manas_id.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
