# Generated by Django 4.2.7 on 2024-01-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manas_id', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
