# Generated by Django 4.2.7 on 2024-01-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manas_id', '0002_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='manasid',
            name='obis_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manasid',
            name='student_id',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
    ]
