# Generated by Django 4.2.7 on 2024-01-02 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manas_id', '0003_manasid_obis_password_manasid_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='manasid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
