# Generated by Django 4.2.7 on 2024-01-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manas_id', '0004_manasid_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='manasid',
            name='personality_type',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
