# Generated by Django 4.2.7 on 2024-01-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manas_id', '0005_manasid_personality_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default='XXX', max_length=3),
            preserve_default=False,
        ),
    ]
