# Generated by Django 4.2.7 on 2024-01-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manas_id', '0006_department_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manasid',
            name='personality_type',
        ),
        migrations.AddField(
            model_name='department',
            name='emoji',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='manasid',
            name='personality_type_prefix',
            field=models.CharField(blank=True, choices=[('INTJ', 'Стратег'), ('INTP', 'Ученый'), ('ENTJ', 'Командир'), ('ENTP', 'Полемист'), ('INFJ', 'Активист'), ('INFP', 'Посредник'), ('ENFJ', 'Тренер'), ('ENFP', 'Борец'), ('ISTJ', 'Администратор'), ('ISFJ', 'Защитник'), ('ESTJ', 'Менеджер'), ('ESFJ', 'Консул'), ('ISTP', 'Виртуоз'), ('ISFP', 'Артист'), ('ESTP', 'Делец'), ('ESFP', 'Развлекатель')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='manasid',
            name='personality_type_suffix',
            field=models.CharField(blank=True, choices=[('A', 'Assertive'), ('T', 'Turbulent')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='manasid',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Female'), (2, 'Male')]),
        ),
    ]
