# Generated by Django 4.2.7 on 2024-01-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manas_id', '0008_alter_department_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manasid',
            name='patronymic',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
