# Generated by Django 4.2.7 on 2024-01-04 08:34

from django.db import migrations, models
import manas_id.models


class Migration(migrations.Migration):

    dependencies = [
        ('manas_id', '0010_country_nationality_region_manasid_nationality_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='manasid',
            options={'verbose_name': 'Manas ID', 'verbose_name_plural': 'Manas IDs'},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'verbose_name_plural': 'nationalities'},
        ),
        migrations.AddField(
            model_name='manasid',
            name='extra_preferences',
            field=models.JSONField(default=list, validators=[manas_id.models.validate_extra_preferences]),
        ),
    ]
