# Generated by Django 4.2.7 on 2024-01-10 17:14

from django.db import migrations, models
import manas_id.models


class Migration(migrations.Migration):

    dependencies = [
        ('manas_id', '0011_alter_country_options_alter_manasid_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manasid',
            name='extra_preferences',
            field=models.JSONField(blank=True, default=list, validators=[manas_id.models.validate_extra_preferences]),
        ),
    ]
