# Generated by Django 4.2.4 on 2023-08-11 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('file_id', models.CharField(max_length=255, unique=True)),
                ('media_type', models.PositiveSmallIntegerField(choices=[(1, 'Photo'), (2, 'Voice'), (3, 'Video'), (4, 'Audio'), (5, 'Animation'), (6, 'Document'), (7, 'Video Note'), (8, 'Sticker')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecretMessage',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecretMessageTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_template_text', models.CharField(max_length=200)),
                ('button_text', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='secretmessagetheme',
            constraint=models.CheckConstraint(check=models.Q(('description_template_text__contains', '{name}')), name='secret_message_template_contains_name', violation_error_message='Secret message template must contain "{name}"'),
        ),
    ]
