# Generated by Django 4.2.3 on 2023-08-01 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_telegram_id'),
        ('secret_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('of_user', 'to_user')},
        ),
    ]
