# Generated by Django 4.2.3 on 2023-08-09 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('secret_messages', '0002_secretmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secretmedia',
            name='media_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Photo'), (2, 'Voice'), (3, 'Video'), (4, 'Audio'), (5, 'Animation'), (6, 'Document'), (7, 'Video Note'), (8, 'Sticker')]),
        ),
    ]
