# Generated by Django 4.2.3 on 2023-08-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_messages', '0002_alter_contact_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretmessage',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
