# Generated by Django 4.2.4 on 2023-08-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_messages', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretmessagetheme',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
