# Generated by Django 4.2.7 on 2024-03-10 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_born_at'),
        ('secret_messages', '0003_secretmessagetheme_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secretmessage',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_secret_message', to='users.user'),
        ),
        migrations.AddField(
            model_name='secretmessage',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secretmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_secret_message', to='users.user'),
        ),
        migrations.AlterField(
            model_name='secretmessage',
            name='text',
            field=models.CharField(max_length=4096),
        ),
    ]
