# Generated by Django 4.2.3 on 2023-08-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_messages', '0003_secretmedia_created_at_secretmessage_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='secretmessagetemplate',
            constraint=models.CheckConstraint(check=models.Q(('text__contains', '{name}')), name='secret_message_template_contains_name'),
        ),
    ]
