# Generated by Django 4.2.7 on 2024-04-05 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_messages', '0004_secretmessage_deleted_at_secretmessage_recipient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecretMessageTheme',
        ),
    ]
