# Generated by Django 4.2.7 on 2024-08-26 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_contact_theme'),
        ('secret_messages', '0005_delete_secretmessagetheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretTextMessage',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contact')),
            ],
        ),
        migrations.DeleteModel(
            name='SecretMessage',
        ),
    ]
