# Generated by Django 4.2.7 on 2024-08-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_messages', '0006_secrettextmessage_delete_secretmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secretmedia',
            old_name='name',
            new_name='caption',
        ),
    ]
