# Generated by Django 4.2.7 on 2024-08-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_messages', '0007_rename_name_secretmedia_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretmedia',
            name='file_id',
            field=models.CharField(max_length=255),
        ),
    ]
