# Generated by Django 4.2.7 on 2024-06-21 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_characteristics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItemAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_characteristics.fooditem')),
            ],
            options={
                'verbose_name': 'food item alias',
                'verbose_name_plural': 'food item aliases',
            },
        ),
    ]
